### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by slavakurilyak** [serverless-components/fullstack-app#5]
When testing the [fullstack-app demo](https://www.serverless-fullstack-app.com/), I am having an issue logging into my account. 

After I click "sign in" button, I am getting a "failed to fetch" error:

`Origin https://www.serverless-fullstack-app.com is not allowed by Access-Control-Allow-Origin`

**Comment by austencollins** [comment]
Hi @slavakurilyak, thanks for the heads up!  Fixed 👍

**Comment by RobAikins** [comment]
I'm getting this issue after I deployed. Out of curiosity, how was it fixed?
