### ISSUE TITLE
Issues upgrading latest version of Serverless 2.31.12

### ISSUE THREAD

**Issue by juampick** [serverless-components/fullstack-app#7]
Hi all, 

I successfully deployed this project to AWS. All was working almost fine. 

But today I upgraded **serverless** component. And I couldn't ever deploy. Nothing is working. 

Please find attached version: 
![image](https://user-images.githubusercontent.com/3301047/86811945-d580df00-c054-11ea-95fc-8c65c0eb7abb.png)

So, now when trying to deploy from root with the provided command: `serverless deploy --all --stage dev` 
![image](https://user-images.githubusercontent.com/3301047/86812214-255fa600-c055-11ea-9e99-9fd9460235c6.png)

Doing the same from `site` or `api` folder is having the same issues. 

Could you please help us?

**Comment by juampick** [comment]
I tried doing what It says in this ticket: https://github.com/serverless/components/issues/641

Basically uninstalling and re-installing. But the same problem. I think this is a bigger issue. 

Do you have any clue? Thanks

**Comment by eahefnawy** [comment]
@juampick we had an issue in our backend yesterday, but we resolved it. I think that might be it. Could you try again?

**Comment by juampick** [comment]
Awesome, I have just tried and worked fine @eahefnawy . I appreciate you replying to me.

**Comment by eahefnawy** [comment]
Great! I appreciate you reporting! ❤️

**Comment by juampick** [comment]
But another question, is that, (before upgrading serverless also) I was having the same issue. 

![WhatsApp Image 2020-07-08 at 11 46 21](https://user-images.githubusercontent.com/3301047/86933308-c9f2ee00-c110-11ea-9090-e0e1ea9c797e.jpeg)

Going to the `site` folder and doing a `serverless deploy --stage dev` (only website) is not working. (It's working from the root doing the `--all`). Not sure why. You can see the error message. 
I searched and I didn't find the solution. Do you know why is happening @eahefnawy ?
